name: lecture_env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11.13
  - ipykernel=6.30.1
  - pip:
      - matplotlib==3.10.6
      - numpy==2.3.2
      - pandas==2.3.2
      - scikit-learn==1.7.2
